// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlsSfk3pDvF_wOIEowteRcZ3AasojFits',
    appId: '1:165662711092:android:426f01039a44f912561961',
    messagingSenderId: '165662711092',
    projectId: 'deck-f429c',
    storageBucket: 'deck-f429c.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcidZbhx94GiVKJE-8skIpsglme8RItGU',
    appId: '1:490568176970:web:aa1761db39316d91b39db3',
    messagingSenderId: '490568176970',
    projectId: 'deck-5195d',
    authDomain: 'deck-5195d.firebaseapp.com',
    storageBucket: 'deck-5195d.appspot.com',
    measurementId: 'G-Z6DJ7GFTRL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgd6w-GondV5iX-Xhq1cwDdFuJTO618dk',
    appId: '1:490568176970:ios:b92b54e1a7f01fedb39db3',
    messagingSenderId: '490568176970',
    projectId: 'deck-5195d',
    storageBucket: 'deck-5195d.appspot.com',
    androidClientId: '490568176970-9a64mlm565jtu09prv5cg0vpklhc8j2p.apps.googleusercontent.com',
    iosClientId: '490568176970-1rhjmjmaqgoqtebikp0d52qm2pel1jnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.deck',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgd6w-GondV5iX-Xhq1cwDdFuJTO618dk',
    appId: '1:490568176970:ios:b92b54e1a7f01fedb39db3',
    messagingSenderId: '490568176970',
    projectId: 'deck-5195d',
    storageBucket: 'deck-5195d.appspot.com',
    androidClientId: '490568176970-9a64mlm565jtu09prv5cg0vpklhc8j2p.apps.googleusercontent.com',
    iosClientId: '490568176970-1rhjmjmaqgoqtebikp0d52qm2pel1jnn.apps.googleusercontent.com',
    iosBundleId: 'com.example.deck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcidZbhx94GiVKJE-8skIpsglme8RItGU',
    appId: '1:490568176970:web:91e22a7ec15fcfaeb39db3',
    messagingSenderId: '490568176970',
    projectId: 'deck-5195d',
    authDomain: 'deck-5195d.firebaseapp.com',
    storageBucket: 'deck-5195d.appspot.com',
    measurementId: 'G-LQM8FPEETN',
  );

}